name: clutch
description: Application for discount ERP

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_translate_annotations: ^1.0.1


  intl: 0.16.1
  cupertino_icons: ^0.1.2
  flutter_staggered_grid_view: 0.3.0
  expandable: ^4.1.2
  flutter_rating_bar: ^1.1.0
  flutter_slidable: "^0.5.4"
  firebase_core: ^0.4.0+9
  firebase_analytics: 5.0.11
  firebase_messaging: 6.0.13
  flutter_bloc: 4.0.0
  equatable: ^1.1.1
  google_maps_flutter: 0.5.26+4
  barcode: 1.8.0
  flutter_translate: ^1.5.7
  package_info: ^0.4.0+6
  dio: 3.0.9
  shared_preferences: 0.5.7
  alice: 0.0.30
  cached_network_image: 2.2.0+1
  datetime_picker_formfield: ^1.0.0
  carousel_slider: 2.1.0
  barcode_flutter: 1.1.2
  pin_code_fields: 3.0.1
  url_launcher: 5.4.10
  geolocator: 5.3.2+2
  permission_handler: 5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
  flutter_translate_gen: ^1.2.4
  build_runner: ^1.8.0


flutter:

  uses-material-design: true

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
        - asset: assets/fonts/GoogleSans-Bold.ttf
        - asset: assets/fonts/GoogleSans-Italic.ttf
        - asset: assets/fonts/GoogleSans-Medium.ttf
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
        - asset: assets/fonts/GoogleSans-MediumItalic.ttf

  assets:
    - assets/images/
    - assets/images/logos/
    - assets/images/offers/
    - assets/i18n/

