name: clutch
description: Application for discount ERP

version: 1.0.9
versionCode: 9

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_translate_annotations: ^1.0.1

  intl: 0.16.1
  cupertino_icons: ^0.1.2
  flutter_staggered_grid_view: 0.3.0
  expandable: ^4.1.2
  flutter_rating_bar: ^1.1.0
  flutter_slidable: ^0.5.4
  firebase_core: 0.5.3
  firebase_analytics: 5.0.11
  firebase_messaging: 6.0.13
  flutter_bloc: 4.0.0
  equatable: ^1.1.1
  google_maps_flutter: 0.5.26+4
  barcode: 1.17.1
  flutter_translate: ^1.5.7
  package_info: ^0.4.0+6
  dio: 3.0.9
  shared_preferences: 0.5.7
  alice: 0.1.5
  cached_network_image: 2.3.3
  datetime_picker_formfield: ^1.0.0
  carousel_slider: 2.3.1
  barcode_flutter: 1.1.2
  pin_code_fields: 3.0.1
  url_launcher: 5.7.10
  geolocator: 6.1.9
 ## permission_handler: 5.0.1
  get_it: 4.0.2
  image_picker: 0.6.7+2
  circle_bottom_navigation: 1.0.6
  flutter_cache_manager: 1.4.1
  flutter_color_models: 0.1.6
  app_review: 2.0.1
  pedantic: 1.9.2
  firebase_crashlytics: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_translate_gen: ^1.2.4
  build_runner: ^1.8.0


flutter:

  uses-material-design: true

  fonts:
    - family: BottomNavigationIcon
      fonts:
        - asset: assets/fonts/bottom_navigation_icon.ttf
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
        - asset: assets/fonts/GoogleSans-Bold.ttf
        - asset: assets/fonts/GoogleSans-Italic.ttf
        - asset: assets/fonts/GoogleSans-Medium.ttf
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
        - asset: assets/fonts/GoogleSans-MediumItalic.ttf


  assets:
    - assets/images/
    - assets/images/logos/
    - assets/images/offers/
    - assets/i18n/


